import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseKey);

// Database schema types will be auto-generated by Supabase CLI
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          name: string;
          email: string;
          age: number;
          height: number;
          weight: number;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      user_preferences: {
        Row: {
          id: string;
          user_id: string;
          dietary_preferences: string[];
          food_preferences: string[];
          daily_calorie_goal: number;
          weekly_calorie_goal: number;
          nutrition_goals: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['user_preferences']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['user_preferences']['Insert']>;
      };
      food_logs: {
        Row: {
          id: string;
          user_id: string;
          food_type: string;
          ingredients: string[];
          portion_size: string;
          calories: number;
          emoji: string;
          logged_at: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['food_logs']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['food_logs']['Insert']>;
      };
      user_progress: {
        Row: {
          id: string;
          user_id: string;
          current_streak: number;
          level: number;
          daily_progress: number;
          weekly_progress: number;
          avatar_state: string;
          last_updated: string;
        };
        Insert: Omit<Database['public']['Tables']['user_progress']['Row'], 'id'>;
        Update: Partial<Database['public']['Tables']['user_progress']['Insert']>;
      };
    };
  };
};