name: Swift CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: Swift Version
        run: swift --version

      - name: Build CalorieCameraKit
        run: swift build
        working-directory: calorie-camera

      - name: Test CalorieCameraKit
        run: swift test
        working-directory: calorie-camera

      - name: Build Demo Application
        run: swift build
        working-directory: calorie-camera-demo
